version: "3.9"
services:
  # Mysl Service
  db:
    image: mysql
    container_name: "${APP_NAME}_mysql"
    volumes:
      - ./mysql/:/var/lib/mysql/
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${APP_NAME}_db"
      - "MYSQL_USER=${APP_NAME}_user"
      - MYSQL_PASSWORD=password
    restart: always
    networks:
      - my_network

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: "${APP_NAME}_phpmyadmin"
    ports:
      - 8081:80
    environment:
      - "MYSQL_USERNAME=${APP_NAME}_user"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - PMA_HOST=db
    restart: always
    networks:
      - my_network

  # Laravel App
  app:
    depends_on:
      - db
    build: 
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    container_name: "${APP_NAME}_laravel"
    restart: always
    volumes:
      - ./laravel/:/var/www
    expose:
      - 9000
    networks:
      - my_network

        
  #Nginx Service
  nginx:
    depends_on:
      - db
      - app
    image: nginx:stable-alpine
    container_name: "${APP_NAME}_nginx"
    volumes:
      - ./laravel/:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 8000:80
    restart: always
    networks:
      - my_network
      
networks:
  my_network:
    name: "${APP_NAME}_docker_network"
    driver: bridge